#!/usr/bin/sh
#
# unify_locales:
#

# Generate translated desktop files  from desktop.in files
msgfmt \
  --desktop \
  --template=data/applications/bodhi-update-manager.in \
  -d po \
  -o data/applications/bodhi-update-manager.desktop
msgfmt \
  --desktop \
  --template="data/applications/bodhi-update-manager-tray.in" \
  -d po \
  -o data/applications/bodhi-update-manager-tray.desktop
# Generate translated policykit file from policy.in file
msgfmt \
  --xml \
  --template="data/polkit/org.bodhi.updatemanager.policy.in" \
  -d po \
  -o "data/polkit/org.bodhi.updatemanager.policy"

intltool-merge -x po \
	"data/polkit/org.bodhi.updatemanager.policy.in" \
	"data/polkit/org.bodhi.updatemanager.policy"
