#!/usr/bin/env bash
set -euo pipefail

VERSION=$(dpkg-parsechangelog -S Version | cut -d- -f1-2)

cat > src/bodhi_update/_version.py <<EOF
"""Version information for the Update Manager."""

__version__ = "${VERSION}"
EOF

